network_type: calico
network_cidr: 192.168.0.0/16
service_cluster_ip_range: 192.168.0.0/24
ingress_enabled: true
ansible_user: root

mesos_enabled: false
install_docker_py: true

sl_datacenter: lon02
sl_ssh_key: 1258983
sl_vlan: 1292651

sl_icp_masters:
  - ed-icp-master-01

sl_icp_workers:
  - ed-icp-worker-01
  - ed-icp-worker-02

sl_icp_proxies:
  - ed-icp-proxy-01
